security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /
                check_path:  /
            logout:
                path:   /players/logout
            remember_me:
                        key:      "%secret%"
                        lifetime: 31536000 # 365 days in seconds
                        path:     /
                        domain:   ~

    access_control:
        - { path: ^/bet, roles: ROLE_PLAYER }

    providers:
            players:
                entity: { class: CoreBetBundle:Players, property: nick }

    encoders:
            Core\BetBundle\Entity\Players:
                algorithm:        sha256
                encode_as_base64: false
                iterations:       1

