security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /
                check_path:  /
            remember_me:
                        key:      "%secret%"
                        lifetime: 31536000 # 365 days in seconds
                        path:     /
                        domain:   ~

    access_control:
        - { path: ^/bet, roles: ROLE_USER }

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: kitten, roles: 'ROLE_USER' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
